package entity
// Code generated by sql2gorm. DO NOT EDIT.


import (
	_ "time"
)

type Admin struct {
	Model
	ID        int64     `gorm:"column:f_id;primary_key;AUTO_INCREMENT"` // 自增id
	UserName  string    `gorm:"column:f_user_name;NOT NULL"`            // 用户名
	Password  string    `gorm:"column:f_password;NOT NULL"`             // 密码
}

func (m *Admin) TableName() string {
	return "t_admin"
}

